name: diet_recipe_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  url_launcher: ^6.3.1
  dio: ^4.0.0
  path_provider: ^2.0.0
  connectivity_plus: ^6.1.0
  dots_indicator: ^3.0.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.11
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.7
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  sms_autofill: ^2.4.0
  intl: ^0.19.0
  pinput: ^5.0.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_datepicker: ^27.1.57
  firebase_core: ^3.8.0
  http: ^1.2.2
  file_picker: ^8.1.4
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikMedium.ttf
          weight: 500
