import 'controller/number_of_snacks_controller.dart';import 'package:flutter/material.dart';import 'package:diet_recipe_app/core/app_export.dart';import 'package:diet_recipe_app/widgets/custom_elevated_button.dart';class NumberOfSnacksScreen extends GetWidget<NumberOfSnacksController> {const NumberOfSnacksScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.black900.withOpacity(0.53), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.53), image: DecorationImage(image: AssetImage(ImageConstant.imgPlanduration), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Spacer(), Container(padding: getPadding(left: 20, top: 26, right: 20, bottom: 26), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(height: getVerticalSize(27), text: "msg_number_of_snacks".tr, rightIcon: Container(margin: getMargin(left: 30), child: CustomImageView(svgPath: ImageConstant.imgClose)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onTap: () {onTapNumberof();}), Padding(padding: getPadding(top: 22), child: Text("lbl_1_snacks".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_2_snacks".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_3_snacks".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_4_snacks".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_5_snacks".tr, style: theme.textTheme.bodyLarge))]))]))))); } 
/// Navigates to the chooseYourPlanStandardTabContainerScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the chooseYourPlanStandardTabContainerScreen.
onTapNumberof() { Get.toNamed(AppRoutes.chooseYourPlanStandardTabContainerScreen, ); } 
 }
