import 'controller/verification_confirm_controller.dart';import 'package:flutter/material.dart';import 'package:diet_recipe_app/core/app_export.dart';import 'package:diet_recipe_app/widgets/custom_elevated_button.dart';class VerificationConfirmScreen extends GetWidget<VerificationConfirmController> {const VerificationConfirmScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer, body: SizedBox(height: mediaQueryData.size.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage13, height: getVerticalSize(924), width: getHorizontalSize(428), alignment: Alignment.center), Opacity(opacity: 0.5, child: Align(alignment: Alignment.center, child: Container(padding: getPadding(left: 20, top: 267, right: 20, bottom: 267), decoration: AppDecoration.black, child: Container(padding: getPadding(left: 23, top: 32, right: 23, bottom: 32), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgThumbs1, height: getSize(132), width: getSize(132)), Padding(padding: getPadding(top: 21), child: Text("msg_password_changed".tr, style: theme.textTheme.titleLarge)), Container(width: getHorizontalSize(341), margin: getMargin(top: 12), child: Text("msg_your_password_has".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge!.copyWith(height: 1.56))), CustomElevatedButton(text: "lbl_ok".tr, margin: getMargin(top: 31), onTap: () {onTapOk();})])))))])))); } 
/// Navigates to the loginScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the loginScreen.
onTapOk() { Get.toNamed(AppRoutes.loginScreen, ); } 
 }
