import 'controller/onboarding_one_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:diet_recipe_app/core/app_export.dart';import 'package:diet_recipe_app/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class OnboardingOneScreen extends GetWidget<OnboardingOneController> {const OnboardingOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer, body: SizedBox(height: getVerticalSize(879), width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: SizedBox(height: getVerticalSize(571), width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgFlatlaycompos, height: getVerticalSize(571), width: getHorizontalSize(428), alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: getPadding(left: 20, top: 19, right: 20, bottom: 19), decoration: AppDecoration.gradientBlackToOnPrimary, child: GestureDetector(onTap: () {onTapTxtSkip();}, child: Text("lbl_skip".tr, style: CustomTextStyles.bodyLargeOnPrimaryContainer))))]))), Align(alignment: Alignment.bottomCenter, child: Container(padding: getPadding(left: 20, top: 36, right: 20, bottom: 36), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgFrameOnprimarycontainer), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_deliicious_food".tr, style: theme.textTheme.headlineMedium), Container(width: getHorizontalSize(361), margin: getMargin(left: 12, top: 23, right: 13), child: Text("msg_arguably_south_india_s".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeOnError_1.copyWith(height: 1.56))), Container(height: getVerticalSize(8), margin: getMargin(top: 52), child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: appTheme.lightGreen600, dotColor: appTheme.blueGray100, dotHeight: getVerticalSize(8), dotWidth: getHorizontalSize(8)))), CustomElevatedButton(text: "lbl_next".tr, margin: getMargin(top: 49, bottom: 3), onTap: () {onTapNext();})])))])))); } 
/// Navigates to the loginScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the loginScreen.
onTapTxtSkip() { Get.toNamed(AppRoutes.loginScreen, ); } 
/// Navigates to the onboardingTwoScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the onboardingTwoScreen.
onTapNext() { Get.toNamed(AppRoutes.onboardingTwoScreen, ); } 
 }
