import 'controller/select_month_controller.dart';import 'package:flutter/material.dart';import 'package:diet_recipe_app/core/app_export.dart';import 'package:diet_recipe_app/widgets/custom_elevated_button.dart';class SelectMonthScreen extends GetWidget<SelectMonthController> {const SelectMonthScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.black900.withOpacity(0.53), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.53), image: DecorationImage(image: AssetImage(ImageConstant.imgPlanduration), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Spacer(), Container(padding: getPadding(left: 20, top: 26, right: 20, bottom: 26), decoration: AppDecoration.white.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(height: getVerticalSize(27), text: "lbl_select_month".tr, rightIcon: Container(margin: getMargin(left: 30), child: CustomImageView(svgPath: ImageConstant.imgClose)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onTap: () {onTapSelectmonth();}), Padding(padding: getPadding(top: 24), child: Text("lbl_january".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_feruary".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 19), child: Text("lbl_march".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 22), child: Text("lbl_april".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_may".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 19), child: Text("lbl_june".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 22), child: Text("lbl_july".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_august".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 20), child: Text("lbl_septeber".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 19), child: Text("lbl_october".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_november".tr, style: theme.textTheme.bodyLarge)), Padding(padding: getPadding(top: 21), child: Text("lbl_deceber".tr, style: theme.textTheme.bodyLarge))]))]))))); } 
/// Navigates to the chooseYourPlanStandardTabContainerScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the chooseYourPlanStandardTabContainerScreen.
onTapSelectmonth() { Get.toNamed(AppRoutes.chooseYourPlanStandardTabContainerScreen, ); } 
 }
